# DESCRIPTION:
# Creates the Spirometry register unit test input table.
#
# PARAMETERS:
#
# - schema_etl_input: path to schema with the input tables for the ETL.

BEGIN
DROP TABLE IF EXISTS @schema_etl_input.spirometry;

CREATE TABLE @schema_etl_input.spirometry (
  FINNGENID STRING,
	APPROX_DATE DATE,
	SOURCE STRING,
	SEX STRING,
	BIRTH_DATE STRING,
	AGE_AT_TEST FLOAT64,
	AGE_GROUP STRING,
	IS_PEDIATRIC BOOL,
	HEIGHT_BEST FLOAT64,
	HEIGHT_CLEAN FLOAT64,
	HEIGHT_FLAG STRING,
	WEIGHT_MEDIAN FLOAT64,
	WEIGHT_LATEST FLOAT64,
	WEIGHT_CLEAN FLOAT64,
	WEIGHT_FLAG STRING,
	FEV1_BEST FLOAT64,
	FVC_BEST FLOAT64,
	FEV1_FVC_RATIO FLOAT64,
	FEV1_MAX FLOAT64,
	FVC_MAX FLOAT64,
	MEASUREMENT_TYPE STRING,
	FEV1_POST FLOAT64,
	FVC_POST FLOAT64,
	FEV1_FVC_POST FLOAT64,
	FEV1_CHANGE_L FLOAT64,
	FEV1_CHANGE_PCT FLOAT64,
	FVC_CHANGE_L FLOAT64,
	FVC_CHANGE_PCT FLOAT64,
	SIGNIFICANT_RESPONSE STRING,
	OBSTRUCTION STRING
);

END;
