# DESCRIPTION:
# Creates the Drug Events unit test input table.
#
# PARAMETERS:
#
# - schema_etl_input: path to schema with the input tables for the ETL.

BEGIN
DROP TABLE IF EXISTS @schema_etl_input.drug_events;

CREATE TABLE @schema_etl_input.drug_events (
  FINNGENID STRING,
  PRESCRIPTION_ID STRING,
  PRESCRIPTION_APPROX_EVENT_DAY DATE,
  PRESCRIPTION_AGE FLOAT64,
  PRESCRIPTION_ATC STRING,
  PRESCRIPTION_VNR STRING,
  MEDICATION_APPROX_EVENT_DAY DATE,
  MEDICATION_AGE FLOAT64,
  MEDICATION_ATC STRING,
  MEDICATION_VNR STRING,
  MEDICATION_QUANTITY FLOAT64,
  MERGED_SOURCE STRING,
  INDEX STRING
);

END;
