# DESCRIPTION:
# Creates the Kanta register unit test input table.
#
# PARAMETERS:
#
# - schema_etl_input: path to schema with the input tables for the ETL.

BEGIN
DROP TABLE IF EXISTS @schema_etl_input.kanta;

CREATE TABLE @schema_etl_input.kanta (
  FINNGENID STRING,
  TEST_DATE_TIME DATETIME,
  AGE_AT_MEASUREMENT FLOAT64,
  TEST_SERVICE_PROVIDER STRING,
  TEST_ID STRING,
  TEST_ID_SOURCE INT64,
  TEST_NAME_ABBREVIATION STRING,
  MEASUREMENT_VALUE FLOAT64,
  MEASUREMENT_UNIT STRING,
  RESULT_ABNORMALITY STRING,
  MEASUREMENT_STATUS STRING,
  TEST_REFERENCE_TEXT STRING,
  TEST_REFERENCE_GROUP STRING,
  TEST_REFERENCE_MIN_VALUE FLOAT64,
  TEST_REFERENCE_MIN_UNIT STRING,
  TEST_REFERENCE_MAX_VALUE FLOAT64,
  TEST_REFERENCE_MAX_UNIT STRING,
  IS_UNIT_VALID STRING,
  mappingStatus STRING,
  sourceCode STRING,
  conceptId INT64,
  `ADD_INFO:omopQuantity` STRING,
  MEASUREMENT_VALUE_SOURCE FLOAT64,
  MEASUREMENT_UNIT_SOURCE STRING,
  TEST_NAME_ABBREVIATION_SOURCE STRING

);

END;
