# DESCRIPTION:
# Creates the kidney register unit test input table.
#
# PARAMETERS:
#
# - schema_etl_input: path to schema with the input tables for the ETL.

BEGIN
DROP TABLE IF EXISTS @schema_etl_input.kidney;

CREATE TABLE @schema_etl_input.kidney (
  FINNGENID STRING,
  EVENT_AGE FLOAT64,
  APPROX_EVENT_DAY DATE,
  START_YEAR INT64,
  KIDNEY_DISEASE_DIAGNOSIS_1 STRING,
  KIDNEY_DISEASE_DIAGNOSIS_2 STRING,
  ERA_EDTA_DIAGNOSIS INT64,
  EDTA_DIAGNOSIS_OLD INT64,
  APPROX_END_DATE_OF_TRACKING DATE,
  END_OF_TRACKING_AGE FLOAT64,
  HEIGHT INT64,
  WEIGHT FLOAT64,
  SYSTOLIC_BLOOD_PRESSURE INT64,
  DIASTOLIC_BLOOD_PRESSURE INT64,
  CHOLESTEROL FLOAT64,
  HDL_CHOLESTEROL FLOAT64,
  TRIGLYCERIDE FLOAT64,
  PREVIOUS INT64,
  `CURRENT` INT64,
  APPROX_START_DATE_OF_NERF_TRACKING DATE,
  START_OF_NERF_TRACKING_AGE FLOAT64,
  ANGINA_PECTORIS INT64,
  HEART_ATTACK INT64,
  BYPASS_OR_OTHER_PROCEDURE INT64,
  LEFT_VENTRICULAR_HYPERTROPHY INT64,
  HEART_FAILURE INT64,
  OTHER_VASCULAR_DISEASE INT64,
  OTHER_VASCULAR_DISEASE_ENTRY INT64,
  OTHER_VASCULAR_DISEASE_AMPUTATION INT64,
  DYSLIPIDEMIA_DIET_TREATMENT INT64,
  DYSLIPIDEMIA_MEDICAL_TREATMENT INT64,
  STROKE INT64,
  RR_MEDICAL_TREATMENT INT64,
  T1D INT64,
  T2D INT64,
  UNKNOWN_TYPE_OF_DIABETES INT64,
  IV_IRON INT64,
  VITAMIN_D_TREATMENT INT64,
  EPO_TREATMENT INT64,
  FISTULA_IN_FIRST_DIALYSIS_TREATMENT INT64,
  APPROX_DIABETES_DATE DATE,
  DIABETES_AGE FLOAT64,
  REASON_FOR_TERMINATION_OF_ACTIVE_TREATMENT STRING,
  PREVIOUS_FORM_OF_TREATMENT INT64,
  CURRENT_FORM_OF_TREATMENT INT64,
  TYPE_OF_CHANGE STRING,
  YEAR INT64,
  FISTULA INT64,
  ANTIHYPERTENSIVE_DRUG INT64,
  ESA_TREATMENT INT64,
  DIALYSIS_PER_WEEK FLOAT64,
  DIALYSIS_H_PER_WEEK FLOAT64,
  AZATHIOPRINE INT64,
  CICLOSPORIN INT64,
  TACROLIMUS INT64,
  MYCOPHENOLATE INT64,
  STEROIDS INT64,
  OTHER_IMMUNOSUPPRESSIVE INT64,
  ON_TRANSFER_LIST_OR_NOT INT64,
  PRODUCTION_OF_URINE INT64,
  PERITONITIS_PER_YEAR INT64
);

END;
