# DESCRIPTION:
# Creates the Kanta register unit test input table.
#
# PARAMETERS:
#
# - schema_etl_input: path to schema with the input tables for the ETL.

BEGIN
DROP TABLE IF EXISTS @schema_etl_input.kanta;

CREATE TABLE @schema_etl_input.kanta (
  FINNGENID STRING,
  EVENT_AGE FLOAT64,
  APPROX_EVENT_DATETIME DATETIME,
  TEST_NAME STRING,
  TEST_ID STRING,
  TEST_ID_SYSTEM INT64,
  CONCEPT_ID INT64,
  MEASUREMENT_VALUE FLOAT64,
  MEASUREMENT_UNIT STRING,
  MEASUREMENT_VALUE_HARMONIZED FLOAT64,
  MEASUREMENT_UNIT_HARMONIZED STRING,
  RESULT_ABNORMALITY STRING,
  MEASUREMENT_STATUS STRING,
  REFERENCE_RANGE_MIN_VALUE FLOAT64,
  REFERENCE_RANGE_MAX_VALUE FLOAT64,
  CODING_SYSTEM STRING,
  TEST_ID_SOURCE STRING,
  TEST_NAME_SOURCE STRING,
  MEASUREMENT_VALUE_SOURCE FLOAT64,
  MEASUREMENT_UNIT_SOURCE STRING
);

END;
