# DESCRIPTION
# Split a table in service-sector format into register tables and copies finngenid_info to the schema used as input for the etl.
#
# PARAMETERS
#
# - schema_table_service_sector: schema and table indicating the table in service-sector format to transform
# - schema_table_finngenid: schema and table indicating the  finngenid_info table to copy
#
# - schema_etl_input: schema containing the output tables used as input in the etl, tables created with create_etl_input_tables_ddl.sql

#
# Empty tables
#
TRUNCATE TABLE @schema_etl_input.finngenid_info;
TRUNCATE TABLE @schema_etl_input.hilmo;
TRUNCATE TABLE @schema_etl_input.reimb;
TRUNCATE TABLE @schema_etl_input.death;
TRUNCATE TABLE @schema_etl_input.prim_out;
TRUNCATE TABLE @schema_etl_input.canc;
TRUNCATE TABLE @schema_etl_input.purch;

#
# FINNGENID_INFO
#
INSERT INTO @schema_etl_input.finngenid_info (
  FINNGENID,
  BL_YEAR,
  BL_AGE,
  SEX,
  HEIGHT,
  HEIGHT_AGE,
  WEIGHT,
  WEIGHT_AGE,
  SMOKE2,
  SMOKE3,
  SMOKE5,
  SMOKE_AGE,
  regionofbirth,
  regionofbirthname,
  movedabroad,
  NUMBER_OF_OFFSPRING,
  APPROX_BIRTH_DATE,
  FU_END_AGE
)
SELECT FINNGENID,
       BL_YEAR,
       BL_AGE,
       SEX,
       HEIGHT,
       HEIGHT_AGE,
       WEIGHT,
       WEIGHT_AGE,
       SMOKE2,
       SMOKE3,
       SMOKE5,
       SMOKE_AGE,
       regionofbirth,
       regionofbirthname,
       movedabroad,
       NUMBER_OF_OFFSPRING,
       APPROX_BIRTH_DATE,
       FU_END_AGE
FROM @schema_table_finngenid
LIMIT @finngenid_limit;


#
# HILMO
#
INSERT INTO @schema_etl_input.hilmo
(
  FINNGENID,
  SOURCE,
  EVENT_AGE,
  APPROX_EVENT_DAY,
  CODE1_ICD_SYMPTOM_OPERATION_CODE,
  CODE2_ICD_CAUSE_NA,
  CODE3_ATC_CODE_NA,
  CODE4_HOSPITAL_DAYS_NA,
  CODE5_SERVICE_SECTOR,
  CODE6_SPECIALITY,
  CODE7_HOSPITAL_TYPE,
  CODE8_CONTACT_TYPE,
  CODE9_URGENCY,
  ICDVER,
  CATEGORY,
  INDEX
)
SELECT
    DL.FINNGENID AS FINNGENID,
    DL.SOURCE AS SOURCE,
    DL.EVENT_AGE AS EVENT_AGE,
    DL.APPROX_EVENT_DAY AS APPROX_EVENT_DAY,
    DL.CODE1 AS CODE1_ICD_SYMPTOM_OPERATION_CODE,
    DL.CODE2 AS CODE2_ICD_CAUSE_NA,
    DL.CODE3 AS CODE3_ATC_CODE_NA,
    DL.CODE4 AS CODE4_HOSPITAL_DAYS_NA,
    DL.CODE5 AS CODE5_SERVICE_SECTOR,
    DL.CODE6 AS CODE6_SPECIALITY,
    DL.CODE7 AS CODE7_HOSPITAL_TYPE,
    DL.CODE8 AS CODE8_CONTACT_TYPE,
    DL.CODE9 AS CODE9_URGENCY,
    DL.ICDVER AS ICDVER,
    DL.CATEGORY AS CATEGORY,
    DL.INDEX AS INDEX
  FROM @schema_table_service_sector as DL
  WHERE DL.SOURCE IN ('INPAT','OUTPAT','OPER_IN','OPER_OUT');

#
# REIMB
#
INSERT INTO @schema_etl_input.reimb
(
  FINNGENID,
  SOURCE,
  EVENT_AGE,
  APPROX_EVENT_DAY,
  CODE1_KELA_DISEASE,
  CODE2_ICD,
  CODE3_NA,
  CODE4_NA,
  ICDVER,
  CATEGORY,
  INDEX
)
SELECT
    FINNGENID AS FINNGENID,
    SOURCE AS SOURCE,
    EVENT_AGE AS EVENT_AGE,
    APPROX_EVENT_DAY AS APPROX_EVENT_DAY,
    CODE1 AS CODE1_KELA_DISEASE,
    CODE2 AS CODE2_ICD,
    CODE3 AS CODE3_NA,
    CODE4 AS CODE4_NA,
    ICDVER AS ICDVER,
    CATEGORY AS CATEGORY,
    INDEX AS INDEX
  FROM @schema_table_service_sector
  WHERE SOURCE = 'REIMB';

#
# DEATH
#
INSERT INTO @schema_etl_input.death
(
  FINNGENID,
  SOURCE,
  EVENT_AGE,
  APPROX_EVENT_DAY,
  CODE1_CAUSE_OF_DEATH,
  CODE2_NA,
  CODE3_NA,
  CODE4_NA,
  ICDVER,
  CATEGORY,
  INDEX
)
SELECT
    FINNGENID AS FINNGENID,
    SOURCE AS SOURCE,
    EVENT_AGE AS EVENT_AGE,
    APPROX_EVENT_DAY AS APPROX_EVENT_DAY,
    CODE1 AS CODE1_CAUSE_OF_DEATH,
    CODE2 AS CODE2_NA,
    CODE3 AS CODE3_NA,
    CODE4 AS CODE4_NA,
    ICDVER AS ICDVER,
    CATEGORY AS CATEGORY,
    INDEX AS INDEX
  FROM @schema_table_service_sector
  WHERE SOURCE = 'DEATH' ;


#
# PRIM_OUT
#
INSERT INTO @schema_etl_input.prim_out
(
  FINNGENID,
  SOURCE,
  EVENT_AGE,
  APPROX_EVENT_DAY,
  CODE1_CODE,
  CODE2_NA,
  CODE3_NA,
  CODE4_NA,
  CODE5_CONTACT_TYPE,
  CODE6_SERVICE_SECTOR,
  CODE7_PROFESSIONAL_CODE,
  ICDVER,
  CATEGORY,
  INDEX
)
SELECT
    DL.FINNGENID AS FINNGENID,
    DL.SOURCE AS SOURCE,
    DL.EVENT_AGE AS EVENT_AGE,
    DL.APPROX_EVENT_DAY AS APPROX_EVENT_DAY,
    DL.CODE1 AS CODE1_CODE,
    DL.CODE2 AS CODE2_NA,
    DL.CODE3 AS CODE3_NA,
    DL.CODE4 AS CODE4_NA,
    DL.CODE5 AS CODE5_CONTACT_TYPE,
    DL.CODE6 AS CODE6_SERVICE_SECTOR,
    DL.CODE7 AS CODE7_PROFESSIONAL_CODE,
    DL.ICDVER AS ICDVER,
    DL.CATEGORY AS CATEGORY,
    DL.INDEX AS INDEX
  FROM @schema_table_service_sector AS DL
  WHERE DL.SOURCE = 'PRIM_OUT' ;


#
# DEATH
#
INSERT INTO @schema_etl_input.canc
(
  FINNGENID,
  SOURCE,
  EVENT_AGE,
  APPROX_EVENT_DAY,
  CODE1_TOPO,
  CODE2_MORPHO,
  CODE3_BEH,
  CODE4_NA,
  ICDVER,
  CATEGORY,
  INDEX
)
SELECT
    FINNGENID AS FINNGENID,
    SOURCE AS SOURCE,
    EVENT_AGE AS EVENT_AGE,
    APPROX_EVENT_DAY AS APPROX_EVENT_DAY,
    CODE1 AS CODE1_TOPO,
    CODE2 AS CODE2_MORPHO,
    CODE3 AS CODE3_BEH,
    CODE4 AS CODE4_NA,
    ICDVER AS ICDVER,
    CATEGORY AS CATEGORY,
    INDEX AS INDEX
  FROM @schema_table_service_sector
  WHERE SOURCE = 'CANC' ;

#
# PURCH
#
INSERT INTO @schema_etl_input.purch
(
  FINNGENID,
  SOURCE,
  EVENT_AGE,
  APPROX_EVENT_DAY,
  CODE1_ATC_CODE,
  CODE2_SAIR,
  CODE3_VNRO,
  CODE4_PLKM,
  CODE5_REIMBURSEMENT,
  CODE6_ADDITIONAL_REIMBURSEMENT,
  CODE7_REIMBURSEMENT_CATEGORY,
  ICDVER,
  CATEGORY,
  INDEX
)
SELECT
    DL.FINNGENID AS FINNGENID,
    DL.SOURCE AS SOURCE,
    DL.EVENT_AGE AS EVENT_AGE,
    DL.APPROX_EVENT_DAY AS APPROX_EVENT_DAY,
    DL.CODE1 AS CODE1_ATC_CODE,
    DL.CODE2 AS CODE2_SAIR,
    DL.CODE3 AS CODE3_VNRO,
    DL.CODE4 AS CODE4_PLKM,
    DL.CODE5 AS CODE5_REIMBURSEMENT,
    DL.CODE6 AS CODE6_ADDITIONAL_REIMBURSEMENT,
    DL.CODE7 AS CODE7_REIMBURSEMENT_CATEGORY,
    DL.ICDVER AS ICDVER,
    DL.CATEGORY AS CATEGORY,
    DL.INDEX AS INDEX
  FROM @schema_table_service_sector AS DL
  WHERE DL.SOURCE = 'PURCH' ;



