atlasdev:
  connection:
    dbms: bigquery
    user: ""
    password: ""
    connectionString: jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;ProjectId=atlas-development-270609;OAuthType=0;OAuthServiceAcctEmail=146473670970-compute@developer.gserviceaccount.com;OAuthPvtKeyPath=C:\Users\Localadmin_padmanab\Documents\FinnGen\keys.json;Timeout=10000;)"
    pathToDriver: ./db_drivers/bigquery
  # id to source tables, service sector data and finngenid data
  schema_table_service_sector: atlas-development-270609.sandbox_tools_r10.finngen_r10_service_sector_detailed_longitudinal_v2
  schema_table_finngenid: atlas-development-270609.sandbox_tools_r10.finngenid_info_r10_v1
  # id to schema with the input tables for the ETL. Service sector is split in to registers and copied here.
  schema_etl_input: atlas-development-270609.etl_input
  # id to support tables used during ETL
  schema_table_codes_info: atlas-development-270609.medical_codes.fg_codes_info_v2
  schema_table_finngen_vnr: atlas-development-270609.medical_codes.finngen_vnr_v1
  # id to schemas with the output omop vocabulary and cdm
  schema_vocab: atlas-development-270609.cdm_vocabulary
  schema_cdm_output: atlas-development-270609.etl_sam_dev_omop
  # path to omop vocabulary tables
  path_omop_vocab_zip: C:\Users\Localadmin_padmanab\Documents\FinnGen\ETLv2\finngen_finomop_vocabulary.zip
atlasdev_unittest:
  connection:
    dbms: bigquery
    user: ""
    password: ""
    connectionString: jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;ProjectId=atlas-development-270609;OAuthType=0;OAuthServiceAcctEmail=146473670970-compute@developer.gserviceaccount.com;OAuthPvtKeyPath=C:\Users\Localadmin_padmanab\Documents\FinnGen\keys.json;Timeout=10000;)"
    pathToDriver: ./db_drivers/bigquery
  # id to schema with the input tables for the ETL. Service sector is split in to registers and copied here.
  schema_etl_input: atlas-development-270609.etl_sam_unittest_input
  # id to support tables used during ETL
  schema_table_codes_info: atlas-development-270609.medical_codes.fg_codes_info_v2
  schema_table_finngen_vnr: atlas-development-270609.medical_codes.finngen_vnr_v1
  # id to schemas with the output omop vocabulary and cdm
  schema_vocab: atlas-development-270609.cdm_vocabulary
  schema_cdm_output: atlas-development-270609.etl_sam_unittest_omop
