title: FinnGen ETL to OMOP CDM
description: FinnGen ETL to OMOP CDM
theme: just-the-docs

logo: "/assets/images/finngen_icon.avif"

url: https://github.com/FINNGEN/ETL

aux_links:
  "ETL vDF11.0":
    - "https://github.com/FINNGEN/ETL"
aux_links_new_tab: true

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.2.3"

heading_anchors: true

nav_external_links:
  - title: ETL repository on GitHub
    url: https://github.com/FINNGEN/ETL
    hide_icon: false # set to true to hide the external link icon - defaults to false
  - title: Give feedback
    url: https://github.com/FINNGEN/ETL/issues/new
    hide_icon: false # set to true to hide the external link icon - defaults to false


